server:
  port: 8081
spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017,localhost:27018,localhost:27019,localhost:27020,localhost:27021/admin"
      #uri: "mongodb+srv://admin:admin@demo.uskpz.mongodb.net/demo"
      #host: localhost
      #port: 27017
      #database: demo
      #username: user
      #password: password
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
app:
  requiredNoOfHealthyNode: 4
  replicationLagThershold: 200
  interval: 10000
  independentMonitoringMode: true